config/routes.rb
Rails.application.routes.draw do

  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    passwords: 'customers/passwords',
    registrations: 'customers/registrations'
  }
  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    registrations: 'admin/registrations'
  }
  #admin
  namespace :admin do
    root 'homes#top'
    resources :customer_datas, only: [:show, :index, :edit, :update]
    resources :items, except: [:destroy]
    resources :genres, except: [:new, :show, :destroy]
    resources :orders, only: [:index, :show]
    get '/customer_datas/:id/orders' => 'orders#index', as: "customer_data_orders" # 会員詳細 => 注文履歴の表示データを変える用
    get '/yesterday/orders' => 'orders#index', as: "yesterday_orders" # TOP,本日製作分の注文数 => 注文履歴の表示データ用
    get '/today/orders' => 'orders#index', as: "today_orders" # TOP,本日受注した注文数 => 注文履歴の表示データ用
    patch '/orders/:id/order_status' => 'orders#order_status_update', as: "order_status" # 注文ステータスupdate
    patch '/orders/:id/item_status' => 'orders#item_status_update', as: "item_status" # 製作ステータスupdate
  end
  #customer
  root 'homes#top'
  get '/about' => 'homes#about' #店舗
  get '/thanks' => 'homes#thanks' #サンクスページ
  get '/orders/confirm' => 'orders#confirm', as: 'orders_confirm' #購入確認画面への遷移
  get '/orders/create_order' => 'orders#create_order' #購入確定のアクション
  post '/orders/create_ship_address' => 'orders#create_ship_address' #情報入力画面での配送先登録用のアクション
  delete '/cart_items' => 'cart_items#destroy_all' #カートアイテムを全て削除
  resources :customers, only: [:show, :edit, :update]
  get '/customers/:id/withdrow' => 'customers#withdrow', as: 'withdrow_customer' #退会画面への遷移
  patch '/customers/:id/withdrow' => 'customers#switch', as: 'withdrow_switch_customer' #会員ステータスの切替
  resources :ship_addresses, except: [:new, :show]
  resources :cart_items, except: [:new, :show, :edit]
  resources :items, only: [:index, :show]
  resources :genres, only: [:index] do
  resources :items, only: [:index]
  end
  resources :orders, except: [:edit, :update, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name,  presence: true
  validates :first_name, presence: true
  validates :last_name_kana,  presence: true, format: {with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}
  validates :first_name_kana, presence: true, format: {with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}
  # カタカナ制限
  validates :phone_number, presence: true, format: {with: /\A\d{10}$|^\d{11}\z/, message: '10桁か11桁の電話番号を入力してください。'}
  # ！！！電話番号の検証は現状空白のみ！！！
  validates :post_code,  presence: true, format: {with: /\A\d{7}\z/}
   # 郵便番号のフォーマット指定 ハイフン無し７桁固定 Viewのフォーム設定
  validates :address, presence: true
  has_many :cart_items, dependent: :destroy
  has_many :ship_addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :configure_permitted_parameters, if: :devise_controller?
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  private
  def after_sign_in_path_for(resource)
    customer_path(current_customer)
  end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :configure_permitted_parameters, if: :devise_controller?

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  private
  def after_sign_in_path_for(resource)
    if resource.is_enabled == false    #(resource)に入った値の中で、is_enabledがfalseだったら--
       sign_out resource
       root_path
    else
       customer_path(current_customer)
    end
  end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :ensure_correct_customer, {only: [:show, :edit]}
  
  def show
  	@customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:success] = "You have edited user data successfully."
      redirect_to customer_path(@customer)
    else
      render 'edit'
    end
  end

  def withdrow #退会画面を表示するアクション
    @customer = Customer.find(params[:id])
  end

  def switch
    @customer = Customer.find(params[:id])
    if @customer.update(is_enabled: false)
      sign_out current_customer #URLを踏ませずにコントローラーから直接サインアウトの指示を出す（device公式)
    end
    redirect_to root_path
  end



  private
  def customer_params
  	  params.require(:customer).permit(:is_enabled, :last_name, :first_name, :last_name_kana, :first_name_kana,
  	                                   :phone_number, :email, :password, :post_code, :address)
  end

  def ensure_correct_customer
    @customer = Customer.find(params[:id])
    if current_customer.id != @customer.id
       redirect_to root_path
    end
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/edit.html.erb
<div class="container my-5">
  <div class="row">
    <div class="offset-1">
      <h2 class="red-border px-3 pb-1">Profile Edit</h2>
    </div>
  </div>
  <div class="row my-3">
    <div class="offset-3 col-6">
    <%= form_for(@customer) do |f| %>
      <div class="form-group">
        <%= f.label :氏名, class: "brown-border px-3" %>
        <div class="row">
          <%= f.text_field :last_name, class: "form-control offset-1 col-4"%>
          <%= f.text_field :first_name, class: "form-control col-4"%>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :フリガナ, class: "brown-border px-3" %>
        <div class="row">
          <%= f.text_field :last_name_kana, class: "form-control offset-1 col-4"%>
          <%= f.text_field :first_name_kana, class: "form-control col-4"%>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :郵便番号, class: "brown-border px-3" %>
        <%= f.text_field :post_code, class: "form-control offset-1 col-8"%>
      </div>
      <div class="form-group">
        <%= f.label :住所, class: "brown-border px-3" %>
        <%= f.text_field :address, class: "form-control offset-1 col-8"%>
      </div>
      <div class="form-group">
        <%= f.label :電話番号, class: "brown-border px-3" %>
        <%= f.text_field :phone_number, class: "form-control offset-1 col-8"%>
      </div>
      <div class="form-group">
        <%= f.label :メールアドレス, class: "brown-border px-3" %>
        <%= f.email_field :email, class: "form-control offset-1 col-8"%>
      </div>
      <div class="row">
        <%= f.submit "編集内容を保存する", class: "btn btn-outline-danger offset-3 mt-3" %>
      </div>
    <% end %>
    </div>
    <div class="col-2 d-flex flex-column align-items-end">
      <%= link_to "退会する" , withdrow_customer_path(@customer), class: "btn btn-danger mt-auto" %>
    </div>
  </div>
</div>

app/views/customers/show.html.erb
<div class="container my-5">
  <div class="row">
    <div class="offset-sm-1">
	  <h2 class="red-border px-3 pb-1">My Page</h2>
	</div>
  </div>
  <div class="row my-3">
    <div class="offset-sm-3">
	  <strong class="red-border px-3 pb-1">登録情報</strong>
	</div>
  </div>
  <div class="row">
	<div class="offset-sm-4 col-sm-4">
	  <table class="table table-borderless table-hover">
	    <tr class="brown-border">
		  <td>氏名</td>
		  <td>
		    <%= @customer.last_name %>
		    <%= @customer.first_name %>
		  </td>
	    </tr>
	    <tr class="brown-border">
		  <td>フリガナ</td>
		  <td>
		    <%= @customer.last_name_kana %>
		    <%= @customer.first_name_kana %>
	      </td>
	    </tr>
	    <tr class="brown-border">
		  <td>郵便番号</td>
		  <td><%= @customer.post_code %></td>
	    </tr>
	    <tr class="brown-border">
		  <td>住所</td>
		  <td><%= @customer.address %></td>
	    </tr>
	    <tr class="brown-border">
		  <td>電話番号</td>
		  <td><%= @customer.phone_number %></td>
	    </tr>
	    <tr class="brown-border">
	      <td>メールアドレス</td>
	      <td><%= @customer.email %></td>
	    </tr>
	  </table>
	  <div class="row">
	    <%= link_to "編集する", edit_customer_path(@customer), class: "btn btn-outline-danger mx-auto my-1" %>
	  </div>
	  <div class="row">
		<%= link_to "パスワードを変更する", edit_customer_registration_path, class: "btn btn-outline-danger mx-auto my-1" %>
	  </div>
	</div>
	<div class="offset-sm-1 col-sm-3">
	  <div class="row">
	    <%= link_to "配送先一覧を見る", ship_addresses_path, class: "btn btn-primary btn-outline-danger my-1" %>
      </div>
	  <div class="row">
	    <%= link_to "注文一覧を見る", orders_path, class: "btn btn-primary btn-outline-danger my-1" %>
	  </div>
	</div>
  </div>
</div>

app/views/customers/withdrow.html.erb
<div class="container my-5">
  <div class="row">
    <div class="offset-1">
      <h1 class="red-border px-3">本当に退会しますか？</h1>
    </div>
  </div>
  <div class="row my-5">
    <div class="offset-2">
      <p>退会すると、会員登録情報やこれまでの購入履歴が閲覧できなくなります。</p>
      <p>退会する場合は、「退会する」をクリックしてください。</p>
    </div>
  </div>
  <div class="row">
    <div class="offset-3 col-2">
      <%= link_to "退会しない" ,customer_path(current_customer), class: "btn btn-outline-danger" %>
      <!-- 注文履歴一覧へ-->
    </div>
    <div class="offset-2 col-2">
      <%= link_to "退会する" , withdrow_switch_customer_path(@customer),method: :patch, class: "btn btn-danger" %>
      <!-- 会員ステータスを無効に切り替えるswichアクションを呼ぶ-->
    </div>
  </div>
</div>