config/routes.rb
Rails.application.routes.draw do

  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    passwords: 'customers/passwords',
    registrations: 'customers/registrations'
  }
  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    registrations: 'admin/registrations'
  }
  #admin
  namespace :admin do
    root 'homes#top'
    resources :customer_datas, only: [:show, :index, :edit, :update]
    resources :items, except: [:destroy]
    resources :genres, except: [:new, :show, :destroy]
    resources :orders, only: [:index, :show]
    get '/customer_datas/:id/orders' => 'orders#index', as: "customer_data_orders" # 会員詳細 => 注文履歴の表示データを変える用
    get '/yesterday/orders' => 'orders#index', as: "yesterday_orders" # TOP,本日製作分の注文数 => 注文履歴の表示データ用
    get '/today/orders' => 'orders#index', as: "today_orders" # TOP,本日受注した注文数 => 注文履歴の表示データ用
    patch '/orders/:id/order_status' => 'orders#order_status_update', as: "order_status" # 注文ステータスupdate
    patch '/orders/:id/item_status' => 'orders#item_status_update', as: "item_status" # 製作ステータスupdate
  end
  #customer
  root 'homes#top'
  get '/about' => 'homes#about' #店舗
  get '/thanks' => 'homes#thanks' #サンクスページ
  get '/orders/confirm' => 'orders#confirm', as: 'orders_confirm' #購入確認画面への遷移
  get '/orders/create_order' => 'orders#create_order' #購入確定のアクション
  post '/orders/create_ship_address' => 'orders#create_ship_address' #情報入力画面での配送先登録用のアクション
  delete '/cart_items' => 'cart_items#destroy_all' #カートアイテムを全て削除
  resources :customers, only: [:show, :edit, :update]
  get '/customers/:id/withdrow' => 'customers#withdrow', as: 'withdrow_customer' #退会画面への遷移
  patch '/customers/:id/withdrow' => 'customers#switch', as: 'withdrow_switch_customer' #会員ステータスの切替
  resources :ship_addresses, except: [:new, :show]
  resources :cart_items, except: [:new, :show, :edit]
  resources :items, only: [:index, :show]
  resources :genres, only: [:index] do
  resources :items, only: [:index]
  end
  resources :orders, except: [:edit, :update, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
  validates :price, 		  presence: true
  validates :sale_status, presence: true
  # ！！with optionでまとめる！！
  has_many :cart_items, dependent: :destroy
  belongs_to :genre
  attachment :image
  enum sale_status: [:販売可, :販売不可]
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController


before_action :authenticate_admin!

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_items_path
    else
      flash[:item_created_error] = "商品情報が正常に保存されませんでした。"
      redirect_to new_admin_item_path
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    else
      flash[:item_updated_error] = "商品情報が正常に保存されませんでした。"
      redirect_to edit_admin_item_path(@item)
    end
  end

  private
  def item_params
    params.require(:item).permit(:genre_id, :image, :name, :description, :price, :sale_status)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @genres = Genre.where(is_enabled: true)
  	  # ジャンルが有効のみ
      # もしURLに[:genre_id]が含まれていたら
    if params[:genre_id]
      # その[:genre_id]のデータをGenreから@genreに格納
      @genre = Genre.find(params[:genre_id])
      # @genreに紐付いた商品で販売可の商品を引っ張る（作成順の昇順）
      @items = @genre.items.order(created_at: :desc).where(sale_status: "販売可").page(params[:page]).per(8)

      # 含まれていなければ
    else
      @items = Item.where(sale_status: "販売可").page(params[:page]).per(12)
     # 販売ステータスが販売可のみの商品を参照 ジャンル作成の昇順
    end
  end

  def show
    @cart_item = CartItem.new
  	@genres = Genre.all
  	@item = Item.find(params[:id])
  end

end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_admin_header.html.erb
<nav class="navbar navbar-expand navbar-dark bg-dark navbar-fixed-top", style="background-color: #432c28;">
  <div class="container">
    <div class="row">
      <%= link_to "ながのcake管理者サイト", admin_root_path, class: "navbar-brand" %>

      <% if admin_signed_in? %>
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "商品一覧", admin_items_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "会員一覧", admin_customer_datas_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "注文履歴一覧", admin_orders_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "ジャンル一覧", admin_genres_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link" %>
          </li>
        </ul>

        <form class="form-inline">
          <input class="form-control-sm mr-sm-2" type="search" placeholder="検索...機能しないけど..." aria-label="検索...">
          <button type="submit" class="btn btn-outline-light btn-sm my-2 my-sm-0">検索</button>
        </form>
      <% end %>

    </div>
  </div>
</nav>

app/views/items/_genrebox.html.erb
<div class="offset-1 col-10">
  <div class="row d-flex aline-items-center">
    <strong class="red-border px-3 pb-1">ジャンル検索</strong>
  </div>
  <div class="row mx-auto mt-3">
    <span class="brown-border text-center"><%= link_to "すべての商品", items_path %></span>
  </div>
    <% genres.each do |genre| %>
    <%= link_to genre_items_path(genre) do %>
  <div class="row mx-auto mt-3">
    <span class="brown-border text-center"><%= genre.name %></span>
  </div>
  <% end %>
  <% end %>
</div>

app/views/items/index.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-3">
      <%= render 'genrebox', genres: @genres %>
    </div>
    <div class="col-9">
      <!--動的ジャンル名-->
      <div class="row">
        <h2 class="red-border px-3">
          <% if params[:genre_id] %>
            <%= @genre.name %>
          <% else %>
            すべての商品
          <% end %>
        </h2>
      </div>
      <!-- 販売件数 -->
      <div class="row my-3 ml-1">
        <strong class="brown-border">
          全
          <% if params[:genre_id] %>
    	     <%= @items.order(created_at: :desc).where(sale_status: "販売可").count %>
          <% else %>
    		    <%= Item.where(sale_status: "販売可").count %>
          <% end %>
          件
        </strong>
      </div>
      <!-- 動的ジャンル登録アイテム数設定する-->
	  <div class="row">
	    <% @items.each do |item| %>
        <div class="col-3 mt-3"> <!--ひとつのブロックをラップしてカラムを指定する-->
		  <%= link_to item_path(item) do %><!--それをeach文で回す-->
		  <%= attachment_image_tag item, :image, size: "150x150", format: 'jpeg', fallback: "no_image.jpg", class: 'rounded' %>
		  <% end %><br>
		  <span class="text-muted"><%= link_to item.genre.name, genre_items_path(item.genre_id) %></span><br>
		  <strong class="red-border"><%= item.name %></strong><br>
		  <span class="ml-auto"><%= (item.price * 1.1).floor %>円</span><br>
        </div>
      <% end %>
	  </div>
    </div>
  </div>
  	<!-- ページネーション -->
  <div class="container">
    <div class="row">
      <div class="col-md-4 offset-md-4 py-2 mt-5">
        <%= paginate @items %>
      </div>
    </div>
  </div>
 	<!-- ページネーション -->
</div>

app/views/items/show.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-3 mt-4">
      <%= render 'genrebox', genres: @genres %> <!--ジャンル検索-->
    </div>
    <div class="col-9 my-3">
  	  <div class="row">
        <!-- 画像 -->
	    <div class="col-5">
          <%= attachment_image_tag @item, :image, size: '50x50', format: "jpeg", fallback: 'no_image.jpg', size: '300x300', class: "rounded" %>
	    </div>
        <!-- タイトル -->
        <div class="col-5">
          <div class="row">
            <h4 class="red-border px-3 pb-1"><%= @item.name %></h4>
          </div>
          <!-- 説明 -->
          <div class="row mt-3">
            <p class="ml-5"><%= @item.description %></p>
          </div>
          <!-- 価格 -->
          <div class="row">
            <strong class="red-border px-3 ml-auto"><%= (@item.price * 1.1).floor %>円 (税込)</strong>
          </div>
        </div>
      </div>
      <!-- 個数選択 -->
      <div class="row">
        <div class="offset-6">
          <div class="row">
            <%= form_for (@cart_item) do |f| %>
              <%= f.number_field :quantity, min:1, placeholder: "個数選択" %><span>個</span>
              <%= f.hidden_field :item_id, :value => @item.id %>
              <%= f.submit "カートに入れる", class: "btn btn-outline-danger" %>
      　　    <% end %>
          </div>
          <div class="row">
            <%= flash[:into_cart_error] %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>