config/routes.rb
Rails.application.routes.draw do

  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    passwords: 'customers/passwords',
    registrations: 'customers/registrations'
  }
  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    registrations: 'admin/registrations'
  }
  #admin
  namespace :admin do
    root 'homes#top'
    resources :customer_datas, only: [:show, :index, :edit, :update]
    resources :items, except: [:destroy]
    resources :genres, except: [:new, :show, :destroy]
    resources :orders, only: [:index, :show]
    get '/customer_datas/:id/orders' => 'orders#index', as: "customer_data_orders" # 会員詳細 => 注文履歴の表示データを変える用
    get '/yesterday/orders' => 'orders#index', as: "yesterday_orders" # TOP,本日製作分の注文数 => 注文履歴の表示データ用
    get '/today/orders' => 'orders#index', as: "today_orders" # TOP,本日受注した注文数 => 注文履歴の表示データ用
    patch '/orders/:id/order_status' => 'orders#order_status_update', as: "order_status" # 注文ステータスupdate
    patch '/orders/:id/item_status' => 'orders#item_status_update', as: "item_status" # 製作ステータスupdate
  end
  #customer
  root 'homes#top'
  get '/about' => 'homes#about' #店舗
  get '/thanks' => 'homes#thanks' #サンクスページ
  get '/orders/confirm' => 'orders#confirm', as: 'orders_confirm' #購入確認画面への遷移
  get '/orders/create_order' => 'orders#create_order' #購入確定のアクション
  post '/orders/create_ship_address' => 'orders#create_ship_address' #情報入力画面での配送先登録用のアクション
  delete '/cart_items' => 'cart_items#destroy_all' #カートアイテムを全て削除
  resources :customers, only: [:show, :edit, :update]
  get '/customers/:id/withdrow' => 'customers#withdrow', as: 'withdrow_customer' #退会画面への遷移
  patch '/customers/:id/withdrow' => 'customers#switch', as: 'withdrow_switch_customer' #会員ステータスの切替
  resources :ship_addresses, except: [:new, :show]
  resources :cart_items, except: [:new, :show, :edit]
  resources :items, only: [:index, :show]
  resources :genres, only: [:index] do
  resources :items, only: [:index]
  end
  resources :orders, except: [:edit, :update, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admin/layouts_controller.rb
class Admin::LayoutsController < ApplicationController
end

app/helpers/admin/layouts_helper.rb
module Admin::LayoutsHelper
end

app/views/layouts/_admin_header.html.erb
<nav class="navbar navbar-expand navbar-dark bg-dark navbar-fixed-top", style="background-color: #432c28;">
  <div class="container">
    <div class="row">
      <%= link_to "ながのcake管理者サイト", admin_root_path, class: "navbar-brand" %>
      <% if admin_signed_in? %>
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "商品一覧", admin_items_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "会員一覧", admin_customer_datas_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "注文履歴一覧", admin_orders_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "ジャンル一覧", admin_genres_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link" %>
          </li>
        </ul>
        <form class="form-inline">
          <input class="form-control-sm mr-sm-2" type="search" placeholder="検索..機能しない" aria-label="検索">
          <button type="submit" class="btn btn-outline-light btn-sm my-2 my-sm-0">検索</button>
        </form>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/_customers_header.html.erb
<nav class="navbar navbar-expand navbar-dark navbar-fixed-top", style="background-color: #3eb03a;">
  <div class="container">
    <div class="navbar-header">
      <%= link_to "ながのcake", root_path, class: "navbar-brand" %>
    </div>
    <% if customer_signed_in? %>
      <span class="u h7 text-white strong">
        ようこそ！<%= current_customer.last_name %>
        <%= current_customer.first_name %>さん！
      </span>
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "トップページ", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "マイページ", customer_path(current_customer), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "商品一覧", items_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "カート", cart_items_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "nav-link" %>
        </li>
      </ul>
    <% else %>
      <span class="u h7 text-white strong">
        ようこそ！ゲストさん！
      </span>
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "トップページ", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">  
          <%= link_to "会員登録", new_customer_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "ログイン", new_customer_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "商品一覧", items_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "店舗情報", about_path, class: "nav-link" %>
        </li>
      </ul>
    <% end %>
    </div>
  </nav>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error-explanation" class="alert alert-danger">
  	<h2><%= model.errors.count %> error prohibited this obj from being saved:</h2>
    <ul><% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'  %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<!-- header デザイン分岐 -->
    <header class="header">
      <% if request.fullpath.include? "admin"  %>
        <%= render 'layouts/admin_header' %>
      <% else%>
        <%= render 'layouts/customers_header' %>
      <% end %>
    </header>
    <main>
      <%= yield %>
    </main>
<!-- footer デザイン分岐 -->
    <% if request.fullpath.include? "admin"  %>
      <footer class="footer text-white bg-dark">
    <% else%>
      <footer class="footer text-white", style="background-color: #3eb03a;">
    <% end %>
      <div class="container text-center mt-3">
        <p>© 2021 sakai hiroki inc.</p>
      </div>
    </footer>
  </body>
</html>